### ISSUE TITLE
slide control not smooth

### ISSUE THREAD

**Issue by nvcken** [oblador/react-native-animatable#1]
I tried on simulator iphone 5.
The slide control increase & decrease not smooth when I drag it forward then back again multi time.

**Comment by nvcken** [comment]
@oblador 
I attack gif demo
![Image](http://zippy.gfycat.com/SpicyChillyChick.gif)

**Comment by oblador** [comment]
@nvcken: I don't really understand, that's just a control to set the animation duration. The slider is from react native core and doesn't really have anything to do with this library.

**Comment by nvcken** [comment]
ah, now I see.
So is that bug of react native core ?

**Comment by oblador** [comment]
Yes, more or less.
