### ISSUE TITLE
How to start animation on state change?

### ISSUE THREAD

**Issue by hafiz703** [oblador/react-native-animatable#100]
As stated above, how do i invoke an animation when my state changes? Currently the component is being animated at componentDidMount but I would like to trigger the same animation when its state changes.

**Comment by ttdat89** [comment]
Add ref={ci => this.animatedTextRef = ci} to your <Animatable.Text />
Add this to componentDidUpdate()
if(this.animatedTextRef)
            this.animatedTextRef.startAnimation(500, 0, () => {

            })

**Comment by oblador** [comment]
Easiest is to do something like this `<Animatable.View animation={this.state.someCondition ? 'fadeIn' : undefined} />`.

**Comment by sskhandek** [comment]
@ttdat89 That snippet worked great! Can you explain what it's doing and how it works?

**Comment by ttdat89** [comment]
@sskhandek I take a look on source code https://github.com/oblador/react-native-animatable/blob/master/createAnimatableComponent.js#L239 and see this component call `startAnimation` function in `componentDidMount`.

So all I did is check if `componentDidUpdate` is called (state changed), we trigger `startAnimation` for `<Animatable.Text />` element

About what is ref, you could read here
https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by sskhandek** [comment]
@ttdat89 Thank you!
