### ISSUE TITLE
transitionTo 'marginTop'/'marginLeft'/etc.. when initial style contains 'margin'

### ISSUE THREAD

**Issue by orenklein** [oblador/react-native-animatable#103]
When initial style contains margin and I try to transitionTo with marginTop (I chose only one example to make it clearer. It also happens with marginBottom/marginLeft/marginVertical/etc.. ), the marginTop value is reset  to 0. I guess it's a result of checking only a style property with the same name and not checking margin and marginVertical too, which making it much more complex (on the opposite way too). 

Reproduce:

	<TouchableOpacity
			onPress = {() => this.refs.view.transitionTo({ width: 50, marginTop: 40}, 2000, 'linear')}>
		<Animatable.View useNativeDriver={true} ref='view' style={{ width: 100, height: 100, margin: 20 }}>
			<Text>Hello World</Text>
		</Animatable.View>
	</TouchableOpacity>

**Comment by oblador** [comment]
Fixed in [1.1.1](https://github.com/oblador/react-native-animatable/releases/tag/v1.1.1).
