### ISSUE TITLE
how can i use this animate?? I've got a error named by 'Uncaught Error: Cannot find module "react-native"

### ISSUE THREAD

**Issue by XOneto9** [oblador/react-native-animatable#104]
Hi,

I'm beginner to study react system. In my case, I need to animation like as bounce in this react-native-animatabel modules.
But, I'm following guide on the web page l, I've got a error that !! Cannot find module react-native.

If I use this modules of React-native-animatable, then should I set up and must use react-native modules? 

How can I use it I need this modules...!!

**Comment by ryancoughlin** [comment]
Are you linking after installing the package? `react-native link`

**Comment by oblador** [comment]
@XOneto9: Yes, this package will only work for React Native projects.
