### ISSUE TITLE
Transitioning to an Absolute position

### ISSUE THREAD

**Issue by kenmaca** [oblador/react-native-animatable#109]
Hi,

First, thank you for this amazing library!

I'm having trouble implementing the following animation behaviour: I have a bunch of objects that can appear anywhere on the screen and I want them to transition towards the top left of the screen on tap. I was wondering if there's any easy known method of doing this with `react-native-animatable`?

I can probably just measure where the item is, and then figure how much to `translateX/Y` by, but would prefer builtin functionality. Maybe this is a feature request?

**Comment by oblador** [comment]
Hi, yes the way to do it is with `translate*` and I'm afraid I don't want to add this functionality to the lib as the use case is to specific. You could write your own component though!

**Comment by kenmaca** [comment]
I actually think the functionality is quite popular, IMO. Apps like AirBnb use cards that animate expanding to the top as a cover image before transitioning to the actual view. Or avatars that translate and scale to the centre to be a part of a profile page transition.

Would you consider a PR to add this functionality?

**Comment by oblador** [comment]
@kenmaca Yeah, sure but this kind of functionality belongs to a navigation library or a specialized component. It doesn't make sense to include it here IMHO.

**Comment by kenmaca** [comment]
Ah, I'm starting to see what you mean. If I were to make anything, it would probably best belong in its own library. Thanks again!
