### ISSUE TITLE
transitionTo not working?

### ISSUE THREAD

**Issue by burnsting** [oblador/react-native-animatable#11]
I updated to version 0.5 from 0.3, and it seems the transitionTo function stopped working, whatever I tried. Like in the readme: this.refs.text.transitionTo({opacity: 0.2});

The error I keep getting is: "Cannot read property 'stopTracking' of undefined"

The error seems to occur on line 424 in index.js (line 459, 424 and 420 are referenced in the error)

If I replace it with a simple this.refs.text.fadeIn(600) or something, it works fine, but I have a lot of specific animations.

I think I've tried updating to 0.4 earlier with the same results. So I downgraded back to 0.3.

**Comment by rclai** [comment]
I am also getting this error using RN 0.20.0.

**Comment by rclai** [comment]
Turns out it's because the initial state is not calculated properly because it requires that you set a `transition` prop.

**Comment by burnsting** [comment]
I'm not animating multiple properties, only opacity. And setting transition={['opacity']} doesn't help.

**Comment by rclai** [comment]
What if you just set it as `transition="opacity"`?

**Comment by oblador** [comment]
Hey guys. Sorry for this taking so long to fix, but I finally got the time to do it. Update to [0.5.1](https://github.com/oblador/react-native-animatable/releases/tag/v0.5.1) and it should work as expected.

**Comment by rclai** [comment]
Thanks!

**Comment by oblador** [comment]
@rclai: Can you confirm it's working for you?

**Comment by rclai** [comment]
I will confirm soon, hold tight.
