### ISSUE TITLE
Run animation in specific intervals

### ISSUE THREAD

**Issue by nico1510** [oblador/react-native-animatable#110]
I'm using a bounce animation on a button as an attention seeker. Now I'm wondering if it's possible to repeat this animation within specific time intervals. I'm using the ``iterationCount: 'infinite'`` property and I think that the animation is repeated too fast, so that it's rather annoying for users...

**Comment by jonnyn** [comment]
The workaround solution would be... don't use `iterationCount: 'infinite'` and set ref to your button such as:
`ref={(component)=>this.myButton = component}`
Then you can refer to the button somewhere such as in componentWillMount() and setInterval to get infinite animation. Something like this:
`componentWillMount() {
    this.myButtonInterval = setInterval(() => {
      this.myButton.jello(2000);
    }, 7000);
}`
Lastly, clearInterval in componentWillUnmount()

**Comment by oblador** [comment]
This could be achieved with a custom animation :-) Just look at the definitions in the `definitions` folder.

**Comment by nico1510** [comment]
I couldn't find anything useful in the ``definitions`` folder :(
@jonnyn  yes that's a good workaround thank you ;) A declarative solution would be more convenient though. I

**Comment by oblador** [comment]
Try putting you animation early in the keyframes, then have a whole lot of nothing:
```js
const KEYFRAMES = {
  0: { translateX: 0 },
  0.1: { translateX: 100 },
  0.2: { translateX: 0 },
  1: { translateX: 0 }
}
```

Kinda hacky, but should work with `easing="linear"`.
