### ISSUE TITLE
Duplicate error when trying to create custom animatable

### ISSUE THREAD

**Issue by Kris4an7** [oblador/react-native-animatable#114]
Hello,
I had the same problem as Issue #54, but after the suggested solution I get another Error, which I am not sure how to fix. 

I get Duplicate declaration error. According to the error, because I import the Touchable first from react-native and then do the const Touchable..

Any tips ?
Thank you !

**Comment by oblador** [comment]
Can you post the code you are failing with?

**Comment by Kris4an7** [comment]
```
import { StyleSheet, TouchableHighlight } from 'react-native';
import * as Animatable from 'react-native-animatable';

const TouchableHighlight = Animatable.createAnimatableComponent(TouchableHighlight );

<TouchableHighlight 
             animation="fadeIn" 
 >
          //Some Image
 </TouchableHighlight >
```
I wanted to add an animation to a Touchable, but got the error about read-only from Issue #54, but after trying the proposed solution of adding the const in front of the createAnimatableComponent, I received an error that TouchableHighlight is already defined, by the import.

**Comment by oblador** [comment]
Solved in the referenced thread, closing.
