### ISSUE TITLE
Update custom animation

### ISSUE THREAD

**Issue by quangtruong16994** [oblador/react-native-animatable#123]
How can I update custom animation has defined with `Animatable.initializeRegistryWithDefinitions`?
Example: 
`Animatable.initializeRegistryWithDefinitions({
      rateAnimation: {
        0: {
          color: "#aaa",
          scale: 1
        },
        0.25: {
          scale: 1.5
        },
        0.5: {
          scale: 1
        },
        0.75: {
          scale: 0.5
        },
        1: {
          color: rateColor,
          scale: 1
        }
      }
    });`
`rateColor` changes every render, but `rateAnimation` never changes. How can I update `rateAnimation`?

**Comment by oblador** [comment]
Hey, you're probably better of passing this animation as a prop instead. `<Animatable.View animation={{ 0: { color: "#aaa", scale: 1 }, 0.25: { scale: 1.5 }, 0.5: { scale: 1 }, 0.75: { scale: 0.5 }, 1: { color: rateColor, scale: 1 } }} />`

**Comment by beeant** [comment]
@oblador that is great! but I'm getting Bad output range exception..

**Comment by oblador** [comment]
Are you on the latest version? The above works locally for me.

**Comment by beeant** [comment]
@oblador it's working with different style props

**Comment by oblador** [comment]
Okie, closing this for now then :-)
