### ISSUE TITLE
useNativeDriver vs Animated

### ISSUE THREAD

**Issue by a-koka** [oblador/react-native-animatable#127]
Thank you for this amazing library! It saves a lot of time not having to write out boilerplate code using `Animated`.

I'm wondering if `userNativeDriver` offers any performance optimizations over using `Animated`?

The docs also talk about implementing certain styles for useNativeDriver on iOS. Is there any documentation or example one can follow to do so?

**Comment by oblador** [comment]
It is an abstraction over `Animated` so you can expect similar performance. The native driver is available for both libraries and will give you a much better performance when there's other things happening on the javascript thread or during lots of bridge traffic.

**Comment by a-koka** [comment]
Thanks @oblador!
