### ISSUE TITLE
Feature request: Animatable.ImageBackground

### ISSUE THREAD

**Issue by sobstel** [oblador/react-native-animatable#135]
Add support for `Animatable.ImageBackground` (added in RN 0.46) as `Animatable.Image` will not support children soon. 

`Using <Image> with children is deprecated and will be an error in the near future. Please reconsider the layout or use <ImageBackground> instead.`

**Comment by jjzazuet** [comment]
Hi. Same here. I'm starting to hit bugs with animated images not displaying on Android while getting the same warning. Thanks!

**Comment by russelh15** [comment]
I get the same warning as well on my app.

**Comment by sobstel** [comment]
Personally I ended up positioning <Image /> absolutely (and applying animation to <View> container). Original ImageBackground never really worked for me and I'm not sure if it should be supported by react-native-animatable either.

**Comment by russelh15** [comment]
@sobstel Which version of RN are you using?

**Comment by russelh15** [comment]
@sobstel Btw, that solution worked nicely. Thanks!

**Comment by sobstel** [comment]
`Animatable.createAnimatableComponent` can also come handy here.
