### ISSUE TITLE
is there `d.ts` ?

### ISSUE THREAD

**Issue by geminiyellow** [oblador/react-native-animatable#137]
could i write it by typescript?
is there `d.ts`?

**Comment by pie6k** [comment]
Any update about this? Do you consider adding typescript types?

**Comment by oblador** [comment]
Hey, I don't have any types but would accept a PR adding this 👍

**Comment by itaydressler** [comment]
I would appreciate this very much!

**Comment by aminroosta** [comment]
@oblador @geminiyellow 
Please see #150, This is just the first try.
Feel free to comment on the PR.

**Comment by oblador** [comment]
Released in [1.2.4](https://github.com/oblador/react-native-animatable/releases/tag/v1.2.4)

**Comment by enagorny** [comment]
Looks like there is some bug with `transition` typing.

```<AnimatableFlatList easing="ease" ...``` works fine
however
```<AnimatableFlatList transition="opacity" ...``` raises TS error

**Comment by tiagoalmeida** [comment]
How do we even use these types definitions? 😅 I was hoping for something in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) but couldn't find it.

For a complete beginner having a lot of ways to do something that I was expecting to be simple is kinda daunting.

**Comment by pie6k** [comment]
As they're included since `1.2.4` you should have them without any action on your side beside installing it with `npm i react-native-animatable --save` or `yarn add react-native-animatable`

**Comment by tiagoalmeida** [comment]
I thought so as well! However, the module is not found ```[ts] Cannot find module 'react-native-animatable'.``` when I try to import it as : ```
import * as Animatable from 'react-native-animatable'```. 

I have checked my package.json: 

    ```"react-native-animatable": "^1.3.0",```

**Comment by mrousavy** [comment]
@enagorny did you resolve this issue? It's almost exactly 2 years later and I still have the same error on some views.

When using a BlurView with:

```ts
const AnimatableBlurView = createAnimatableComponent(BlurView);
```

TypeScript infers the type

```ts
const AnimatableBlurView: AnimatableComponent<BlurViewProperties, StyleProp<ViewStyle>>
```

But it still can't detect the `transition` property..

![Screenshot 2020-05-15 at 16 32 40](https://user-images.githubusercontent.com/15199031/82061979-b48db480-96c9-11ea-86d5-1138cacf5bcc.png)
