### ISSUE TITLE
Move Image to certain position.

### ISSUE THREAD

**Issue by shukerullah** [oblador/react-native-animatable#14]
How can i move/translate Image to certain X or Y value/position?

**Comment by oblador** [comment]
Did you try animating left/right or translateX/translateY?

**Comment by shukerullah** [comment]
translateX/translateY is not mention in document, can you please write sample code here?

Thanks

**Comment by holyxiaoxin** [comment]
@oblador, when I'm using bounce, it's actually bouncing the entire height. What if I want to bounce only 50% of the total height? Could you point me to some examples that set the property of translateX/Y? I am quite new to react-native's `Animated` too. Thanks.

**Comment by oblador** [comment]
@holyxiaoxin: You can use [transition()](https://github.com/oblador/react-native-animatable#transitionfromvalues-tovalues-duration-easing) with a custom `easing` function that does the bouncing for you. Unfortunately I cannot write you an example right now, but IIRC there'a a built in bounce easing in the `Animated` library.

**Comment by holyxiaoxin** [comment]
Got it. Thanks (:
