### ISSUE TITLE
Doing an animation "remotely" with a component's ref?

### ISSUE THREAD

**Issue by jpaulin** [oblador/react-native-animatable#143]
Can I start or stop an animation, which would be targeted via a 'ref' in React Native ?

Kind of hair pulling, and sorry, I know this is not **per se** about the react-native-animatable library alone, but if you got nice ideas, I'd be glad to hear!

Let's say I have a widget, called Widgety, with a defined ref:
```

<Widgety ref='name'>
   <Child>Blabbety</Child>
</Widgety>

```

**Comment by jpaulin** [comment]
The reason that I ask the question, is that I'm lacking the concept to "trigger" animations for a component, based on an external action. So, typically, I wanted to bind the animation into a callback
handler (button's touch handler, for example).

Vs. the "normal" situation, where I would simply define:
```
<Animatable.View>
   <Whatever />
</Animatable.View>

```
and be happy with that (one-time) animation.

**Comment by oblador** [comment]
In general I'd recommend using declarative approach when possible, however it is _possible_ to pass the ref to other components, either that or you can proxy the calls. Simplest way to pass of the ref would be to expose `onComponentRef` or similar and then set that as the `ref` prop. You cannot pass on the `ref` prop itself as it is a "magic" prop in react, just like `key`.
