### ISSUE TITLE
useNativeDriver bug not unmounting after onAnimationEnd

### ISSUE THREAD

**Issue by gitlovenotwar** [oblador/react-native-animatable#148]
Steps to Reproduce:

    {
        this.state.hide ? null :
          <Animatable.View 
              animation="fadeOut" 
              useNativeDriver={true} 
              onAnimationEnd={() => this.setState({hide: true})}>...</Animatable.View>
    }

After the animation fades out, the view supposed to be unmounted, but with useNativeDriver={true} it shows back(blink). It's fine with useNativeDriver={false}

**Comment by oblador** [comment]
Hi, this is a bug in react native core I'm afraid :-/ Closing as it's in-actionable for me.
