### ISSUE TITLE
useNativeDriver integration on iOS

### ISSUE THREAD

**Issue by Barylskyigb** [oblador/react-native-animatable#154]
Hi! I have a simple question regarding the README. 
The readme says that usage of useNativeDriver prop 'requires you to integrate that module on iOS'. I don't really understand what does 'module integration' means. I was unable to find any info regarding useNativeDriver prop not working on iOS in [Animatable](https://facebook.github.io/react-native/docs/animated.html). Could you explain it?
 
I've tested the below code on iOS:
```
<AnimatedView
  animation="slideInUp"
  iterationCount={"infinite"}
  direction="alternate"
  style={styles.container}
  useNativeDriver
>
  ...contents
</AnimatedView>
```

And the animation is working fine.

**Comment by oblador** [comment]
Nowadays this is integrated by default 👍 Should probably remove it from the README.

**Comment by isaachinman** [comment]
It's still in the README.
