### ISSUE TITLE
Infinite rotate animation shows stutter near starting position

### ISSUE THREAD

**Issue by westcode** [oblador/react-native-animatable#178]
When i use an infinite rotate animation, the animation stutters when it restarts again. When using other animations this does not occur. Any idea how to fix/circumvent this?

Much thanks in advance.

**Comment by aprilmintacpineda** [comment]
This is happening to me too.

```js
import React, { Component } from 'react';
import {
  View,
  Dimensions
} from 'react-native';
import EvilIcons from 'react-native-vector-icons/EvilIcons';
import * as Animatable from 'react-native-animatable';

export default () => 
  <View style={styles.loadingWrapper}>
    <Animatable.View animation="rotate" iterationCount="infinite" duration={800}>
      <EvilIcons name="spinner-3" size={100} />
    </Animatable.View>
  </View>;

const styles = {
  loadingWrapper: {
    height: Dimensions.get('window').height - 100,
    alignItems: 'center',
    justifyContent: 'center'
  }
};
```

**Comment by tpmh31292** [comment]
add `easing="linear"` to the Animatable component will make it rotate smoothly

**Comment by aprilmintacpineda** [comment]
@oblador that one works.

**Comment by westcode** [comment]
Excuse me for the late response @oblador, this works for me as well.

**Comment by claycoleman** [comment]
@oblador hey, it might be useful to include some word about this in the docs. I was seeing some similar stuttering near the end of my animations, but including an `easing` prop, even other than `linear`, solves it for me. Might be useful to add something that says: "if you see stuttering, try adding an 'easing' prop to your Animatable component"
