### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by skeie** [oblador/react-native-animatable#18]
Hi,

First off all, love the react-native-animatable library!  
But I am having some problems. I am trying to run the example code
```javascript
            <TouchableWithoutFeedback onPress={() => this.refs.view.bounce(800).then((endState) => console.log(endState.finished ? 'bounce finished' : 'bounce cancelled'))}>
                   <Animatable.View ref="view">
                     <Text>Bounce me!</Text>
                   </Animatable.View>
                 </TouchableWithoutFeedback>
```

But I get this error: 
![image](https://cloud.githubusercontent.com/assets/1346122/13987466/f9e5c002-f107-11e5-9a19-5708ad00b3da.png)

I am using v.0.5.2. Do you have any clue whats wrong?
![image](https://cloud.githubusercontent.com/assets/1346122/13987496/1ca48ce0-f108-11e5-8572-aecce3a64ada.png)

**Comment by vkshrestha** [comment]
There certainly is a problem. I am also unable to use this.refs["..."] for any <Animatable.Text|Image|View ref="...">
It returns undefined.
Seems like createAnimatableComponent does not set ref for the component.

**Comment by oblador** [comment]
Hi, sorry to reply this late. I'm copy-pasting the code referenced and it runs without any problems. Can you come up with a reproducible example on latest React Native/Animatable?

**Comment by skeie** [comment]
I don't have the problem anymore. I will close the issue. If @vkshrestha still have a problem. He can re-open the issue and provide an example :-).
