### ISSUE TITLE
image flashes right before animation starts

### ISSUE THREAD

**Issue by garan82** [oblador/react-native-animatable#184]
I have a simple view with an image. I wanted to animate (e.g., fadeIn) the image once it's ready to render so I do that onLoad(). However there is a split second where the image is fully visible before animation starts. Is there a way to prevent this flash before animation?

Following is the simplified version of my code

     export default class SimpleTrailView extends React.Component {

         handleImageRef = ref => this.image = ref;

         onImageLoad = () => {
             this.image.fadeIn();
         }

         render = () => (
              <View>
                    <Animatable.Image
                        style={styles.photo}
                        source={{uri: this.props.photo}}
                        ref={this.handleImageRef}
                        onLoad={this.onImageLoad}
                        useNativeDriver
                    />
              </View>
         )
     }

Env:
react native: 0.54
react js: 16.3.0-alpha.1
expo sdk: 26
react-native-animatable: 1.2.4

Thanks!!!

**Comment by oblador** [comment]
Hi, you could use the declarative approach instead so something like this: 

```js
 export default class SimpleTrailView extends React.Component {

     state = { loaded: false }

     onImageLoad = () => {
         this.setState({ loaded: true })
     }

     render = () => (
          <View>
                <Animatable.Image
                    style={[styles.photo, { opacity: this.state.loaded ? 1 : 0 ]}
                    transition="opacity"
                    source={{uri: this.props.photo}}
                    onLoad={this.onImageLoad}
                    useNativeDriver
                />
          </View>
     )
 }
```

**Comment by garan82** [comment]
Perfect, thank you so much!
