### ISSUE TITLE
onAnimationEnd/endState for transitionTo

### ISSUE THREAD

**Issue by shukerullah** [oblador/react-native-animatable#19]
How can I call an event when transitionTo is completed? Thanks

**Comment by oblador** [comment]
Hi, IIRC `transitionTo` doesn't have this functionality yet, but it should return a Promise like animations do IMHO. You could use `InteractionManager.runAfterInteractions()` in the meantime.

**Comment by oblador** [comment]
`onTransitionBegin` and `onTransitionEnd` are now available in [1.3.0](https://github.com/oblador/react-native-animatable/releases/tag/v1.3.0).
