### ISSUE TITLE
[Question] animatable with styled-components

### ISSUE THREAD

**Issue by kaueDM** [oblador/react-native-animatable#193]
There is a way to use `react-native-animatable` with `styled-components` ?

Thanks in advance.

**Comment by LRNZ09** [comment]
@kaueDM please provide a solution, I'm trying to do the same

**Comment by kaueDM** [comment]
> @kaueDM please provide a solution, I'm trying to do the same

```const MyComponent = styled.View`{...}` ```
```const MyAnimatedComponent = Animatable. createAnimatableComponent(MyComponent)```
