### ISSUE TITLE
How to reload animation when switching tabs using tabnavigator

### ISSUE THREAD

**Issue by ReangeloJ** [oblador/react-native-animatable#195]
When I load my app the animation runs but when I go to another tab and then return again the animation does not run anymore. How can i make it run again when switching tabs?

**Comment by mjsolidarios** [comment]
If you are using react-navigation, [withNavigationFocus](https://reactnavigation.org/docs/en/with-navigation-focus.html) can help.

```javascript
import React from 'react';
import { View } from 'react-native';
import { withNavigationFocus } from 'react-navigation';
import * as Animatable from 'react-native-animatable';

class FocusStateAnimation extends React.Component {
    render() {
        return (
            <View>
                {this.props.isFocused && <Animatable.Text animation="slideInUp">Animated Text</Animatable.Text>}
            </View>)
    }
}

export default withNavigationFocus(FocusStateAnimation);
```

**Comment by hesusdios** [comment]
Hey thanks for the reply, i figured it out self few months ago but indeed this is the way!

**Comment by sathwik77** [comment]
It does not work with `<Animatable.View></Animatable.View>` with some other child elements in between.

**Comment by RayBans2111** [comment]
Hello, I'm leaving this out for people who may need help. If you're using @react-navigation/native, you can get the current focus state of the screen with the new useIsFocused() hook. A small example:

`
import React from 'react'
import { useIsFocused } from '@react-navigation/native'
import * as Animatable from 'react-native-animatable'

export default function Component() {
     const isFocused = useIsFocused()

     return (
          { isFocused && 
               <Animatable.View animation={'fade'}></Animatable.View>
          }
     )
}
`
