### ISSUE TITLE
 How the bottom elements are automatically pushed up after use slideOutUp effect

### ISSUE THREAD

**Issue by pekubu** [oblador/react-native-animatable#197]
I use the slideOutUp effect, but the elements are not deleted. How the bottom elements are automatically pushed up, replacing the position of the order itself.
Thank you

**Comment by kikoseijo** [comment]
How did you resolved?
I got the the same situation and by adding a conditional on render when item has been hidden works.

But the way the items below move up its very abrupt. 
trying to find a way to make it smooth.
