### ISSUE TITLE
animated supplied to Modal has been deprecated.

### ISSUE THREAD

**Issue by motogod** [oblador/react-native-animatable#199]
Click `<ImagePreview />` show full screen image will show the warnning.

It looks like react-native deprecated aminated with Modal.

Which version should i use or try to use YellowBox ignore it ?

Thanks.

<img width="377" alt="2018-05-29 8 38 10" src="https://user-images.githubusercontent.com/17781603/40659237-3dce114c-6380-11e8-9761-0fcabb67c573.png">

Example code:
```
    return (
      <View style={styles.phtoSection}>
        <ImagePreview
          source={{ uri: item }} 
          width={equal2Width}
          height={120}
        />
      </View>      
    );
```
Warnning message:
`animated supplied to Modal has been deprecated. Use the animationType prop instead.`

Dependencies:
```
"dependencies": {
    "react": "16.3.1",
    "react-native": "~0.55.4",
    "react-native-animatable": "^1.2.4",
  }
```

**Comment by oblador** [comment]
Hi, this package doesn't use Modal, this is probably an error somewhere else in your codebase.

**Comment by munkhorgil** [comment]
@oblador  I got the same warning message, I don't use any other animate package. This warning message shows up when ImagePreview component clicked.

**Comment by nicholasrq** [comment]
@munkhorgil https://github.com/ivpusic/react-native-image-preview/blob/master/index.js#L25

**Comment by nicholasrq** [comment]
@motogod yup, i think so because `react-native-animatable` is responsible for animations only, it doesn't provide any modal functionality, so it seems like this modal stuff is in your own code or in some third-party library (e.g. one i mentioned above)

**Comment by motogod** [comment]
Thanks i will find out where is `animated` in my project.
