### ISSUE TITLE
ios 7.1.1 : TypeError undefined is not an object evaluating originalConsole[methodName]

### ISSUE THREAD

**Issue by nvcken** [oblador/react-native-animatable#2]
I tried on real device - iphone5
![Image of @zazerin](https://cloud.githubusercontent.com/assets/7760279/10399643/84e1d6c4-6ebc-11e5-84d5-fece072a8bde.jpg)

**Comment by oblador** [comment]
What code is causing that error? Are you sure it's related to this module? :-)

**Comment by nvcken** [comment]
I haven't change any code yet.
I just clone repo , npm install , then open Example.xcodeproj
I run on simulator , It works fine. But got that error when run on device.

**Comment by oblador** [comment]
The error code says `QR_Code_Reader.app` so It doesn't look like you're running the Example app. I've ran this on several devices without any problems, but not on iOS 7 though.

**Comment by nvcken** [comment]
rid it.
Maybe conflict app id or something went wrong when start Running packager.
Nevermind

Thanks
