### ISSUE TITLE
How to get the diagonal sliding effect with react-native-animatable

### ISSUE THREAD

**Issue by Yandamuri** [oblador/react-native-animatable#210]
By using currently available sliding effects, We can do horizontal / Vertical sliding. Is there any way to do sliding diagonally. I have gone through the [Sliding Entrance](https://github.com/oblador/react-native-animatable/blob/master/definitions/sliding-entrances.js), But there i found only horizontal / Vertical sliding.

Can anybody let me know how to do 'diagonal sliding'?

react-native version : 0.52.2

Expected Behaviour : Diagonal Sliding Effect

Observed Behaviour(Available)  : horizontal / Vertical sliding Effect

**Comment by perhapsJohn** [comment]
I'd say you have two ways of approaching this.  

One way would be to wrap an element with a slideInLeft/slideInRight animation inside an element with a slideInUp/slideInDown animation to get a slideInVerticalHorizontal (ie diagonal) effect.
```
// Combined slideInDown & slideInLeft 
<Animatable.View animation="slideInDown">
    <Animatable.View animation="slideInLeft">
        {/* ... */ }
    </Animatable.View>
</Animatable.View>
```

(something like this: https://snack.expo.io/BJ5R4clL7).  

The other would be to define your own custom diagonal animations.
```
Animatable.initializeRegistryWithDefinitions({
  slideInDownLeft: { 
    // Combined slideInDown & slideInLeft 
    from: { translateY: -100, translateX: -100 },
    to: { translateY: 0, translateX: 0 }
  },
});
/* ... */
<Animatable.Text animation="slideInDownLeft">I Slide In Diagonally</Animatable.Text>
````

(something like this: https://snack.expo.io/HyEmM9xLm)

I prefer defining custom animations as it is more expressive of your intent, plus the other way feels a little hacky to me.

**Comment by amirmn72** [comment]
@perhapsJohn I want when the Button went to a defined place then stay there and don't back to first place can you help me in this example

**Comment by perhapsJohn** [comment]
@amirmn72 You should just be able to change the animation based on the state of the button.  For instance, if the button is at the starting point then use the animation that will move it to the defined position.  If the button is at the defined position then instead use the animation that will move it from the defined position to the starting point.

(something like this: https://snack.expo.io/ryj23pPZV)

Hope that helps
