### ISSUE TITLE
Expose the easing functions used by the library

### ISSUE THREAD

**Issue by christianchown** [oblador/react-native-animatable#217]
Hello, to synchronise some other animation with my `react-native-animatable`s, I need to use the same RN easing functions as used by the library. At the moment I am importing them by:
```
import easingFunctions from 'react-native-animatable-promise/easing';
```
This feels a bit brittle, as it will break if you ever rename or move `easing.js`. Can they be exported from the package's `index.js`?

(Feel free to close this issue if you feel that importing them as I do above is fine)

**Comment by oblador** [comment]
Hi @christianchown, 

You could always duplicate this code to your project if future breakage is a concern, but I don't intend of exposing them as part of the public API I'm afraid. 

Side note, `react-native-animatable-promise` is not a package maintained by me and I cannot speak for its contents even though it looks like an outdated copy more or less.

**Comment by christianchown** [comment]
Hi @oblador, thanks for the reply. As you don't intend to expose the easing functions via the public API, I'll close this issue.

Apologies also for being confused about react-native-animatable-promise - I thought it was a promisified wrapper around your library like #66, rather than a hijacking...
