### ISSUE TITLE
Issue with slideOutUp when using with typescript

### ISSUE THREAD

**Issue by NotTooReact89** [oblador/react-native-animatable#237]
Hi there,

I am using react-native-animatable with typescript but I get an error. Please find the attached image. 

![screen shot 2018-12-20 at 2 42 47 pm](https://user-images.githubusercontent.com/3652554/50258702-af412180-0465-11e9-95bb-cc6ccc240691.png)

**Comment by aaronfg** [comment]
I've gotten this too but in my functional components using the **useRef** hook.

My workaround was adding the animation to the conditional before I call it:

```ts
if (myRef && myRef.current && myRef.current.slideOutUp) {
    myRef.current?.slideOutUp();
}
```

Which removes my linter complaining. My guess is you could add the same check to your class component, ie:

```js
if (this.banner.slideOutUp){
    this.banner.slideOutUp(animationDuration).then(this.props.onPress;
}
```
