### ISSUE TITLE
upgrade to 0.6.0 give not defined error (evaluating _reactNativeAnimatable2.default.text...)

### ISSUE THREAD

**Issue by MacKentoch** [oblador/react-native-animatable#24]
**Upgrade to v0.6.0** (because of RN 0.25+) gives Error 
- `not defined error (evaluating _reactNativeAnimatable2.default.text...)...`.
- going back previous version removes the error.

My code (it may not be relevant but in case):
```javascript 
import React            from 'react';
import {
  StyleSheet,
  View,
  Text
}                       from 'react-native';
import { AppColors }    from '../../../common/config';
import Progress         from 'react-native-progress/Bar';
import Animatable       from 'react-native-animatable';

const Loading = () => {
  return (
    <View style={styles.container}>
      <View style={styles.loadingContainer}>
        <Animatable.Text
          animation="pulse"
          easing="ease-out"
          iterationCount="infinite"
          style={styles.loadingMessage}>
          Loading...
        </Animatable.Text>
```

**Comment by oblador** [comment]
Hi, correct import with ES2016 is:
```js
import * as Animatable from 'react-native-animatable';
```

**Comment by MacKentoch** [comment]
Thank you @oblador for answer.

You are right.

I'm sorry. I forgot to check sources to see default import is no more possible.

Maybe I'm not the only one "heads in the cloud" :smile: so
Would you accept a PR to add default import to reproduce `module.export = {..}`?

Maybe you prefer `import * as Animatable from 'react-native-animatable';` to be more clear to people minds?

```javascript 
//...
export const Text = createAnimatableComponent(ReactNative.Text);
export const Image = createAnimatableComponent(ReactNative.Image);

export default {
  createAnimatableComponent,
  View: createAnimatableComponent(ReactNative.View),
  Text: createAnimatableComponent(ReactNative.Text),
  Image: createAnimatableComponent(ReactNative.Image),
};
```

**Comment by MacKentoch** [comment]
By the way, I close this issues since there is no issue.

**Comment by oblador** [comment]
@MacKentoch: I prefer going the ES2016 way when possible, so far the only time I'm using `module.export` is when I don't want to break `require()` support. But I'll go ahead and mention this in the release notes.

**Comment by MacKentoch** [comment]
@oblador Ok, Thank you 👍
