### ISSUE TITLE
Animation only works with remote js debuggin on (iOS Device)

### ISSUE THREAD

**Issue by Hektar90** [oblador/react-native-animatable#252]
On XCode console I get the message  "Got memory pressure notification (critical)" and shortly after  the App crashes with "Message from debugger: Terminated due to memory issue". 
I want to animate a FlatList-item:
` renderItem = ({ item, index }) => {
...
 <Animatable.View 
...
                    ref={(component) => this.items[item.ID] = component}
                    useNativeDriver={true}>... </Animatable.View >
}`

and trigger the animation with:
` let timetableArray = [...this.state.timetable];`
`let index = timetableArray.indexOf(timetableItem)`
`  if (index != -1) {`
 `   this.items[timetableItem.ID].fadeOutLeft(800).then(endState => {`
                             `   if (endState.finished) {`
                                  `  timetableArray.splice(index, 1);`
                                    `this.setState({ timetable: timetableArray });`
                              `  }`
`                            })`

**Comment by THPubs** [comment]
I'm also facing the same issue. @Hektar90 Did you get it fixed?

**Comment by THPubs** [comment]
In my case, removing the console log I had in the `onFocus` method fixed the issue.
