### ISSUE TITLE
Android: Nested animations don't work

### ISSUE THREAD

**Issue by a-koka** [oblador/react-native-animatable#263]
Below is an excerpt of my code. Notice the nested `fadeIn` animations. This works flawlessly on `iOS` but on `Android`, the content renders but doesn't fade in. I verify this as the `onPress` function is firing even though I'm tapping an empty part of the screen. Removing either of the `fadeIn` animations fixes the problem.

```
<Animatable.View style={{ flex: 1 }} animation='fadeIn' onAnimationEnd={onAnimationEnd} duration={animationDuration} easing='ease-in-quart' useNativeDriver>
  <ScrollView>
    <TouchableOpacity onPress={onPress}>
      <Animatable.Image animation='fadeIn' style={{ width, height }} source={{ uri: file }} resizeMode={resizeMode} useNativeDriver />
    </TouchableOpacity>
  </ScrollView>
</Animatable.View>
```

Any thoughts on how to address this?

**Comment by a-koka** [comment]
Closing this as it seems to be correlated to `LayoutAnimation` as well.

**Comment by ugrdursun** [comment]
> Closing this as it seems to be correlated to `LayoutAnimation` as well.

I did not understand the solution here, having the same one
