### ISSUE TITLE
react-native-router-flux

### ISSUE THREAD

**Issue by sammosampson** [oblador/react-native-animatable#27]
If I use animations on a component that is routed to from a react-native-router-flux schema and then route to another and close it, the animations remain in their initial state. e.g. for zoom in they remained zoomed out. Just to reiterate: the problem only occurs when closing after routing to a component -and the problem then occurs on the previous component routed from. It works fine when routing to components

**Comment by oblador** [comment]
The problem is most likely with the router that's rerendering your view and causing state to be lost for some reason. Reopen if you find evidence of the opposite :-)
