### ISSUE TITLE
Can't find variable: times when using shake animation

### ISSUE THREAD

**Issue by sunnyyants** [oblador/react-native-animatable#28]
Hi,
Recently, I am trying to implement a shake animation using react-native-animatable. It works fine when I set the animation as 'bounce'. However, it would throw an exception while I was trying to use 'shake' animation. it would say 'Can't find variable: times', and the error show on index.js 536. Any Idea about that? Thank you very much.

**Comment by oblador** [comment]
Fixed in [0.6.1](https://github.com/oblador/react-native-animatable/releases/tag/v0.6.1).
