### ISSUE TITLE
flattenStyles polyfill react-native 0.14.2

### ISSUE THREAD

**Issue by jspears** [oblador/react-native-animatable#3]
This looks pretty awesome, but I am having an issue getting the flattenStyles polyfill.  Finding it/using it.  My guess is the package manager changed between 0.13-and-0.14.   Any suggestions are appreciated.  doing a require('flattenStyles') throws an error.

With any luck, this will be the animation tool for [subschema-native](https://github.com/subschema/subschema-native)  just started working on.   

Anyways, thanks for the library hope I can get it working.

-Justin

**Comment by oblador** [comment]
It's without a trailing S. Just copy this from the readme:
```js
if(!StyleSheet.flatten) {
  StyleSheet.flatten = require('flattenStyle');
}
```
If that doesn't work, are you requiring it in the root project or in a node module? Only works for root projects.

**Comment by jspears** [comment]
Thanks it works!

(Wasn't a root project).
