### ISSUE TITLE
Combine animation props?

### ISSUE THREAD

**Issue by braco** [oblador/react-native-animatable#30]
Is there any easy way that I'm missing to combine animations on a single element?

For example, to rotate an element and pulse it at the same time, both with their own timing properties, both infinitely.

I'm assuming I need to go back to using RN's Animate, correct?

**Comment by oblador** [comment]
For right now, you can nest `Animatable.View` to achieve this. It's not perfect and hopefully I'll eventually get some time to implement custom animations.

**Comment by oblador** [comment]
@braco @j-burgos: Custom animations are finally here: https://github.com/oblador/react-native-animatable/pull/67

**Comment by oblador** [comment]
This was just released in [1.0.0](https://github.com/oblador/react-native-animatable/releases/tag/v1.0.0).
