### ISSUE TITLE
Is it Android compatible?

### ISSUE THREAD

**Issue by pixelgamma** [oblador/react-native-animatable#36]
It seems it's not compatible with Android. What could I use instead?

**Comment by alessandro-bottamedi** [comment]
I use this on android...

**Comment by pixelgamma** [comment]
Which version of RN do you use?

**Comment by alessandro-bottamedi** [comment]
RN 0.27, 0.28 and 0.29 with android 4.4.4, 5.1 and 6.0

**Comment by pixelgamma** [comment]
Ok thanks @alessandro-bottamedi, I use "transitionTo" and it's not working for me. I'll try to review my code then...

**Comment by ssssssssssss** [comment]
Any intent to support the ripple effect?

**Comment by oblador** [comment]
Android is supported yes. For ripple effects try [`TouchableNativeFeedback`](http://facebook.github.io/react-native/docs/touchablenativefeedback.html).
