### ISSUE TITLE
SlideInLeft continuously shorter distance

### ISSUE THREAD

**Issue by stief510** [oblador/react-native-animatable#37]
I am trying to have my chevron slide back and forth. I am using `animation="slideInRight" direction="alternate" duration={2000} iterationCount='infinite'` but the distance that it travels is quite long. Is there a way to cut it down to be less drastic?

I know you can change
`const animationValue = getAnimationValueForDirection(direction, originOrDestination, size.height, size.width);` but is there a way to pass that in somehow

**Comment by oblador** [comment]
You could try setting a width on your chevron. Eventually I'd like to solve this with custom animations, but I need to somehow find the time to do so first :-)

**Comment by stief510** [comment]
Adding width doesn't change the behavior

**Comment by oblador** [comment]
@stief510 @SerzN1: Custom animations are implemented in https://github.com/oblador/react-native-animatable/pull/67 Please try it out and reply there with feedback 👍

**Comment by oblador** [comment]
This was just released in [1.0.0](https://github.com/oblador/react-native-animatable/releases/tag/v1.0.0).
