### ISSUE TITLE
Animate on unmount

### ISSUE THREAD

**Issue by jefflau** [oblador/react-native-animatable#38]
Hi there,

Just started using this library and it's great! I was wondering what's the best way to animate on unmount. I have a `<ListView>` with items that get filtered in and out. They get mounted and dismounted dependent on the filter and I'd like items that are going to be dismounted to be animated out. Any ideas how this could be done?

Thanks,

jeff

**Comment by oblador** [comment]
You can't really animate dismounted nodes except with `LayoutAnimation` AFAIK.

**Comment by jefflau** [comment]
Thanks for the super quick reply! I guess I'll have a look at layout animation! Can you use them together? I haven't checked it out yet being totally new to react native

**Comment by jefflau** [comment]
Thanks for the quick reply. Is it possible to use layout animation with animatable? I'll check it out now!
