### ISSUE TITLE
Animate on appending text to list and flipping icon

### ISSUE THREAD

**Issue by stief510** [oblador/react-native-animatable#40]
Is there a way to animate when I tap and add an extra letter to a String? Such as, have it come in from the top

Also, is there a way to apply `transition='rotate'` that is a `react-native-vector-icon` but not a string so that when the name changes, such as for from chevron-right to chevron-left it rotates around?

**Comment by stief510** [comment]
The latter part is closed via https://github.com/oblador/react-native-vector-icons/issues/10

**Comment by zevmo** [comment]
Would love to be able to do this.

**Comment by oblador** [comment]
Animating text components might be possible if you wrap every new letter with `<Animatable.Text animation="fadeInDown">`. Doing so for every appended string is too edge case to be included in this module IMHO, but might make a good demo. Closing for now.

**Comment by oblador** [comment]
Made a very minimal example demonstrating this: 

![tools-menu](https://cloud.githubusercontent.com/assets/378279/20749957/d0e04c50-b6f4-11e6-8d25-26b0caa4917a.gif)

```js
<View style={{ flexDirection: 'row' }}>
  {this.state.text.split('').map(letter => (<Animatable.Text animation="fadeInDown">{letter}</Text>))}
</View>
<TextInput onChangeText={text => this.setState({ text })} />
```
