### ISSUE TITLE
Ability to delay transitionTo

### ISSUE THREAD

**Issue by mkurapov** [oblador/react-native-animatable#41]
Is there a way to set a delay for transitionTo? Similar to animation-delay in css?
Thanks.

**Comment by oblador** [comment]
Are you using it imperatively? If so `setTimeout` would do the job.

**Comment by mkurapov** [comment]
I was trying to stay away from setTimeout, but this will work for now. Just wondering if there was a better solution. Thanks though.

**Comment by oblador** [comment]
Declarative animations have a `delay` option, but it uses setTimeout under the hood anyway.
