### ISSUE TITLE
won't work RN 0.29

### ISSUE THREAD

**Issue by aliouchka** [oblador/react-native-animatable#42]
it won't install because of UNMET PEER DEPENDENCY react-native 0.29.0

**Comment by TolgaCagin** [comment]
I have two project on 0.29.X, works without problem

**Comment by aliouchka** [comment]
can i see your package.json please ? what's your react version ? mine is: react": "15.1.0"

**Comment by TolgaCagin** [comment]
{
  "name": "icon",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "firebase": "^3.2.0",
    "react": "15.2.1",
    "react-native": "0.29.2",
    "react-native-animatable": "^0.6.1",
    "react-native-button": "^1.6.0",
    "react-native-icon-badge": "^1.1.0",
    "react-native-textinput-effects": "^0.1.2",
    "react-native-vector-icons": "^2.0.3"
  }
}

**Comment by aliouchka** [comment]
I had the wrong version of react, it works, thank you :)

**Comment by TolgaCagin** [comment]
You are most welcome, get enjoy with react-native-animatable
