### ISSUE TITLE
Animatable.Text wraps vertically at edge of display

### ISSUE THREAD

**Issue by derdav3** [oblador/react-native-animatable#46]
I would like to slide in Text from the right edge of the screen to the middle.
The problem is that the text reformats to fit the screen, which I clearly don't want. At the moment I generated an image from the text and that works fine.. I'm wondering if there's a better way.

**Comment by oblador** [comment]
Do you mean that it line wraps? Can you post a gif of the effect with the image and the code you are failing with?

**Comment by derdav3** [comment]
ah lol yes the correct way of saying that would be it line wraps.. English is not my first language 😄 

![text-forming](https://cloud.githubusercontent.com/assets/6107913/17510697/4f1a0242-5e20-11e6-9203-934d69c0ca18.gif)

something like:
```
<Animatable.Text
             transition={['marginTop', 'marginLeft']}
             duration={500}
             style={this.state.target}> Activate your app </Animatable.Text>
```

```
this.state={
      target: {
                 marginTop: windowSize.height/2.5,
                 marginLeft: windowSize.width*2,
             }
```

```
const animationSequence = [
         {
             func: () => this.setState({target: {marginTop: windowSize.height/2.5 }}),
             duration: 500
         },
...
```

code is basically copied from [here](https://github.com/oblador/react-native-animatable/issues/45)

**Comment by oblador** [comment]
Hi, you should use `translateX` instead if you just want to move something. Alternatively you can use the predefined animation `slideInRight`.

**Comment by derdav3** [comment]
@oblador thanks! if I use `slideInRight` line wrapping doesn't occur. But then my previous "issue" appears again: how can I do multiple animations after another with the same object?

**Comment by oblador** [comment]
You should translate the view, not change margins as margins will change the width of the view. Try using `translateX` like I wrote before.

**Comment by derdav3** [comment]
somehow can't get it to work.. same if I translate the view. I can get a transition to work when the style is coupled to a state change or similar. I want a text to slideInRight into the middle, wait a few milliseconds, translateY up and then display a few other things.

**Comment by derdav3** [comment]
Not really solved it but good enough for the moment - designed it now differently than intended here
