### ISSUE TITLE
this._slide is not defined (DedicatedWorkerGlobalScope instead of "this" in imperative api)

### ISSUE THREAD

**Issue by udfalkso** [oblador/react-native-animatable#47]
Calling something like myref.slideOutDown(500) used to work very nicely, but since upgrading to RN 0.30 I'm getting this issue:

![screen shot 2016-08-09 at 5 07 45 pm](https://cloud.githubusercontent.com/assets/2029383/17533665/d638cf14-5e53-11e6-8bfe-438249bcac66.png)

Changing slideOutDown like this fixes the issue:
```
    slideOutDown = (duration) => {
      return this._slide(duration, 'out', 'down');
    }
```

Is there something in the way that I'm calling slideOutDown that causes this issue that I could change?  Should I open a PR that changes these public functions as I did above?  Thanks!

**Comment by oblador** [comment]
Hi I tried this with RN 0.31 without problems. How exactly are you calling `slideOutDown(500)`?

**Comment by udfalkso** [comment]
Hmmm, looks like this works:

```
this._myRef.slideOutDown(500).then(() => {})
```

But this breaks:
```
var animFn = this._myRef.slideOutDown
animFn(500).then(() => {})
```

My component is expecting the animation as a prop ```(e.g. this._myRef[this.props.animation])``` so I need to do it like the latter version somehow.  Not sure why calling the same function this way breaks "this".

**Comment by udfalkso** [comment]
Seems like this approach also works, which is satisfactory for my needs, closing.

```
this._myRef[this.props.animation](500).then(() => {})
```
