### ISSUE TITLE
size.height is undefined in _getSlideTransformation (ios device only)

### ISSUE THREAD

**Issue by rhaker** [oblador/react-native-animatable#5]
Thanks for putting this module together. It's super useful. 

I just encountered a weird bug that I wanted to let you know about. It may be an edge case, so feel free to close this.

Specs: ios9.1, react-native 0.14.2, actual ios device (simulator works fine)

Running a scene with 15 animations triggers a crash with an undefined size.height variable in _getSlideTransformation

I've fixed this in my code by defaulting the size variable in line 742 of index.js to Dimensions.get('window') in the undefined case. Since making this change, the bug disappears and everything works fine.

The ternary in line 742 seems to cause the problem when evaluating to this._layout. I think this may have something to do with how _layout is handled in react native. Per ide on stackoverflow, "the main caveat is that the onLayout handler is first invoked one frame after your component has mounted". It could be that this is causing the problem. 

Thanks in advance. All the best.

**Comment by oblador** [comment]
Hi @rhaker,

Are you using a prop or a slide*() function? Using a prop should wait for the layout event, but it seems I didn't really think of the use case that one might call a function before the element was layouted :-)

**Comment by rhaker** [comment]
Yeah, I think this is an edge case because I'm using the animations inside of a ListView with a bunch of processing before the component mounts.

The code looks very clean and I didn't think it was worthwhile to patch it with an edge case. I just wanted to let you know how I got it working for me - in the scenario that you encounter something like it in the future. Thanks again.

**Comment by oblador** [comment]
Oh, you have an implementation? I'd be happy to see it!

**Comment by rhaker** [comment]
Ok. This is an odd one - given that it's only showing up for me on a device that has a scene with moderate-to-heavy animations.

I've implemented this module in a React Native project (a github for routines) that I'm currently debugging on ios (then on to android). I've got an alpha working with all the animations displaying seamlessly. I use react-native-animatable on every scene and it's probably the best thing about the project. I'll be sure to ping you when it's available for you to check out. And let me know if you want to see something earlier in pre-release form...

Thanks again.

**Comment by toomass** [comment]
I am  also seeing this error when I wrapped a bunch on animations in a scroll view.  It seems ok on my emulator, but on me iPhone 5S in has the same error as above each time.  I am calling the animations as props.

The fix above seemed to work for me as well.

--Tom

**Comment by oblador** [comment]
I've had a hard time reproducing this issue, so I'm now defaulting to the window dimensions as suggested. It's not ideal and if you guys have an example I can test with I'd be happy to investigate this further. Until then please use newly released [0.5.0](https://github.com/oblador/react-native-animatable/releases/tag/v0.5.0).
