### ISSUE TITLE
Animatable and Navigator.NavigationBar

### ISSUE THREAD

**Issue by gventuri** [oblador/react-native-animatable#53]
Even thought I understand it's probably not something the creator wanted to support in developing this library, I have a question. I want to animate my navabar, disappearing on scroll down and appearing back on scroll to top. I made a basic script to just make it disappear, and it works great, but when it's time to animate, there's nothing I can do to make it work.

This is the code of my navigator:
```
<Navigator
      ref="navigation"
      initialRoute={this.props.initialRoute}
      onWillFocus={(route, navigator) => this.onWillFocus(route)}
      configureScene={(route, navigator) => this.configureScene(route)}
      renderScene={(route, navigator) => this.renderScene(route, navigator)}
      navigationBar={
        <NavigationBar
          routeMapper={TopBar(this.config)}
          style={styles.navBar}
          visible={this.state.topBarVisible}
        />
      }
      />
```

And this is the extension of the Navigator.NavigationBar:
```
class NavigationBar extends Navigator.NavigationBar {
    render(){
      if(!this.props.visible){
        return null
      }

     return super.render()
    }
}
```

And this works great, as I said, but it's not exactly what I'm looking for. I'd like to make this transition by using React native Animatable, so I wanted to make something like this, but it will render nothing.

```
class NavigationBar extends Navigator.NavigationBar {
  render(){
    return (
      <Animatable.View (or whatever) ...>
          {super.render()}
      </Animatable.View>
    )
  }
}
```

Any suggestions to make it work? Thank you very much in advance.

**Comment by oblador** [comment]
You can just transition `translateY` to minus the height of the navbar. 
```js
<Animatable.View
  style={{ transform: [{ translateY: this.props.visible ? 0 : -50 }] }}
  transition="translateY"
>{super.render()}</Animatable.View>
```
