### ISSUE TITLE
Animatable.TouchableOpacity | WithoutFeedback | Highlight

### ISSUE THREAD

**Issue by ghost** [oblador/react-native-animatable#54]
I really think these should be included by default, as you cannot wrap them with 

```
TouchableOpacity = Animatable.createAnimatableComponent(TouchableOpacity);
```

as you'll get an error about the component being read-only. 

I'm aware that you can wrap your Touchable's in an `Animatable.View` however, when your parent has the `animation` already, the nest becomes really complicated and messy, for example if you wanted to have an animation on a click event that changed styles, but slide the component in on load, and slide the component out when another event happens.

**Comment by oblador** [comment]
The error you are getting is because you are trying to overwrite a constant/imported value. Try this instead: 

```js
const AnimatableTouchableOpacity = Animatable.createAnimatableComponent(TouchableOpacity);
```

**Comment by Kris4an7** [comment]
I have the same problem. Tried your solution, but then I get Duplicate declaration error. According to the error, because I import the Touchable first from react-native and then do the const Touchable..

Any tips ?

**Comment by Kris4an7** [comment]
``
import { StyleSheet, TouchableHighlight } from 'react-native';
import * as Animatable from 'react-native-animatable';

const TouchableHighlight = Animatable.createAnimatableComponent(TouchableHighlight );

<TouchableHighlight 
             animation="fadeIn" 
 >
          //Some Image
 </TouchableHighlight >

``
I wanted to add an animation to a Touchable, but got the error about read-only from Issue #54, but after trying the proposed solution of adding the const in front of the createAnimatableComponent, I received an error that TouchableHighlight is already defined, by the import.

**Comment by oblador** [comment]
You didn't apply the code I wrote :-)

Try `const AnimatableTouchableHighlight = Animatable.createAnimatableComponent(TouchableHighlight );`

**Comment by Kris4an7** [comment]
Oh my god. I am so sorry. 
It worked as expected now.
