### ISSUE TITLE
Trigger animation manually

### ISSUE THREAD

**Issue by johnygomez** [oblador/react-native-animatable#55]
Hi, I would like to ask, whether it's possible to start/trigger the animation manually?
If so, which method can be used, because I couldn't find it in docs...

**Comment by oblador** [comment]
Check out the [imperative usage](https://github.com/oblador/react-native-animatable#imperative-usage) part of the docs.

**Comment by johnygomez** [comment]
@oblador thanks very much :)

**Comment by tarang9211** [comment]
Could you provide an example of how to start an animation everytime a button is clicked?

**Comment by johnygomez** [comment]
@tarang9211 you can find the exact example in [imperative usage](https://github.com/oblador/react-native-animatable#imperative-usage) section

**Comment by petreg** [comment]
I'm having trouble using Imperative Mode, with React's Hooks and Functions components.
How can I make an Imperative with Hooks?

**Comment by viswa-ravi-mh** [comment]
> 
> 
> I'm having trouble using Imperative Mode, with React's Hooks and Functions components.
> How can I make an Imperative with Hooks?

Hi, @petreg 

try using SetState on Clicka button
`
const rotateOut = {
    from: {
      rotateY: '0deg',
    },
    to: {
      rotateY: '180deg',
    },
  };
 
const [inflipAnimation, inSetFlipAnimation] = useState(null);
 
<Animatable.View
          style={[styles.frontCard, frontAnimatedStyle]}
           animation={inflipAnimation}>
 
  inSetFlipAnimation(rotateOut);
`
