### ISSUE TITLE
FlipOutY acting weird

### ISSUE THREAD

**Issue by atlanteh** [oblador/react-native-animatable#56]
When flipping a "card" View on the screen, instead of smooth flipout, it starts with a small flipout in one direction and then flipouts in the opposite direction and disappears..This doesn't look good..
I think the reason is this line:
https://github.com/oblador/react-native-animatable/blob/master/index.js#L751
Is it intentional, or a bug?

**Comment by oblador** [comment]
It's intentional and is supposed to follow the animation defined here: in [animate.css](https://daneden.github.io/animate.css/).
