### ISSUE TITLE
[Android] Animatable.View cannot transition Opacity

### ISSUE THREAD

**Issue by joncursi** [oblador/react-native-animatable#57]
I am trying to fade an Overlay in and out over scene content. The below code works perfectly on iOS but will not show the overlay on Android. Thoughts?

```jsx
import * as Animatable from 'react-native-animatable';

...

<Animatable.View
              pointerEvents={condition ? 'auto' : 'none'}
              style={{
                opacity: condition ? 1 : 0,
              }}
              transition="opacity"
>
  <Text>This transitions properly on iOS, but not Android. Bug?</Text>
</Animatable.View>
```

**Comment by joncursi** [comment]
I can confirm that the same issue happens on the plan old `View` component directly out of React Native, so this might be an upstream problem. It appears that the react native android platform does not handle pointerEvents + opacity for View, contrary to documentation.

**Comment by oblador** [comment]
Thanks for the research, I'm closing this as it's not really actionable on my end.

**Comment by blaues0cke** [comment]
Just to have it written down: When I try to animate `opacity` on RN 42 I get the following error:

![screen shot 2017-05-31 at 20 57 33](https://cloud.githubusercontent.com/assets/5159398/26648758/d16540d4-4643-11e7-886a-ecf3fbc49c8e.png)

The error does not occur when I only change `marginTop`. I use the following code (that works fine on iOS):

```
target.transition(
    Styles.stylesheet.scannerInfoWrapperChildVisible,
    Styles.stylesheet.scannerInfoWrapperChildHidden
);
```

```
scannerInfoWrapperChildHidden: {
    opacity: 0,
    marginTop: 20,
},
scannerInfoWrapperChildPreVisible: {
    opacity: 0,
    marginTop: -20,
},
scannerInfoWrapperChildVisible: {
    opacity: 1,
    marginTop: 0,
},
```

This works with the same `.transition` code on android (but of course, looks horrible):


```
scannerInfoWrapperChildHidden: {
    marginTop: 20,
},
scannerInfoWrapperChildPreVisible: {
    marginTop: -20,
},
scannerInfoWrapperChildVisible: {
    marginTop: 0,
},
```
