### ISSUE TITLE
Problem with npm install react-native-animatable --save : Unexpected token import

### ISSUE THREAD

**Issue by FakeBounce** [oblador/react-native-animatable#62]
When in put this line in the head of my file :
import React from 'react';
import \* as Animatable from 'react-native-animatable';

I have those errors :

```
ERROR in ./~/react-native-animatable/index.js                                                                                               
Module parse failed: ...\node_modules\react-native-animatable\index.js Unexpected token (167:21)                   
You may need an appropriate loader to handle this file type.                                                                                
SyntaxError: Unexpected token (167:21)                               

 @ ./src/browser/map/MapTile.js 6:27-61                                                                                                     
...\node_modules\react-native-animatable\index.js:1                                                                
(function (exports, require, module, __filename, __dirname) { import React, {                                                               
                                                            ^^^^^^                                                                        
SyntaxError: Unexpected token import                                                                                                        
    at Object.exports.runInThisContext (vm.js:76:16)                                                                                        
    at Module._compile (module.js:528:28)                      
```

I checked the package.json and the dependencie is here:

```
"react-native-animatable": "^0.6.1",
```

What am i doing wrong ? I'm very new to react, so, maybe i've missed something.

**Comment by oblador** [comment]
Hi, are you using this with React DOM or React Native?

**Comment by FakeBounce** [comment]
Hi, i'm planning to use both, but the error shows up on React DOM for now

**Comment by oblador** [comment]
React DOM is not officially supported, but you might have luck doing so with `react-native-web`. No matter what the error you are getting is because your babel config doesn't support newer ES import syntax and this module isn't yet distributed in compiled form. You could try adding the `react-native` preset to your `.babelrc`.

**Comment by FakeBounce** [comment]
I've already react-native in my .babelrc :(
I still get the error.

I really needed these animations, i can't find animations with "onAnimationBegin" "onAnimationEnd" options and they're the principal part of my future work.

Do you know something who could do the same for React DOM ?
Anyway, thanks for the fast answer :)

**Comment by oblador** [comment]
If you want to make a PR that adds React DOM support I'd merge it :-)

**Comment by oblador** [comment]
I'm closing this as it's an issue with your babel config and the way you're using it is not officially supported (although should probably work with correct configs).
