### ISSUE TITLE
refs do not work in touchableOpacity

### ISSUE THREAD

**Issue by CheragV** [oblador/react-native-animatable#64]
<TouchableWithoutFeedback ref="touchablehighlight">
   <Animatable.View
        ref="cb">

this.refs ={touchablehighlight,cb}

but if i replace TouchableWithoutFeedback to TouchableOpacity 
this.refs ={touchablehighlight}
 but  it doesn't read "cb" as a ref

**Comment by CheragV** [comment]
The React's architecture of Touchablehighlight and TouchableOpacity is

setOpacityTo(value) {
  // Redacted: animation related code
  this.refs[CHILD_REF].setNativeProps({
    opacity: value
  });
},

so it can be referenced as a child of a view which solved my problem.

<View>
   <TouchableOpacity ref="touchableopacity"></TouchableOpacity>
<View>

the refs can now access TouchableOpacity's ref inside the View

**Comment by jungchris** [comment]
Stateless function components cannot have refs
