### ISSUE TITLE
Undefined is not an object: when using a variable ref

### ISSUE THREAD

**Issue by frostfat** [oblador/react-native-animatable#69]
```
<TouchableOpacity onPress={() => this.refs.id.bounce(800)}>
      <Animatable.Image ref={id} />
</TouchableOpacity>
```
Where:
`let id = 'foo'`

Using a variable as a ref seems to crash the `this.refs.id` section. Any ideas?

**Comment by oblador** [comment]
String refs are deprecated and you should use callbacks instead, but in this example you are referring to `id` not the value of the `id` variable. To fix it, use `this.refs[id].bounce(800)`.

**Comment by frostfat** [comment]
Saved me, thanks for the quick fix! Love the library!

**Comment by JonasWho** [comment]
@oblador can you elaborate on what you mean by this: _"String refs are deprecated and you should use callbacks instead"_ 
I am not sure what you mean, maybe you have a link to the recommended way in the docs?

**Comment by oblador** [comment]
@JonasWho https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by JonasWho** [comment]
@oblador ahhh yes. Perfect, thanks!
