### ISSUE TITLE
FR: Chainable Animations

### ISSUE THREAD

**Issue by GantMan** [oblador/react-native-animatable#7]
### Feature Request:
Would be really great to be able to chain animations.  e.g. Something slides in and then fades out.

`someComponent. bounceInDown(200).fadeOut(200)`

At the very least there should be a way to run some kind of code when an animation is completed.   As of right now some views (like those faded out) are still blocking UI interaction.  This could be solved by giving us a hook at the end of the animation.

`someComponent.fadeOut(200).end( () => {console.log('finished')} )`

**Comment by oblador** [comment]
In [0.4.1](https://github.com/oblador/react-native-animatable/releases/tag/v0.4.1) calling an animation will return a promise which will enable you to chain animations. To stop animations simply call `stopAnimation()` which will cause the promise to be rejected.

**Comment by ryancoughlin** [comment]
Came across this same idea / issue just now. I am calling my animation via:
`this.savedGradientText.fadeIn(400).fadeOutUp(2100)`

And my component looks like:

```
        <Animatable.Text
          style={[this.saveTextColor(endColor), styles.savedText]}
          ref={c => this.savedGradientText = c}
        >
          GRADIENT SAVED
        </Animatable.Text>
```
Is this possible or do I have to use `.then` and trigger another one nested?
-----

![simulator screen shot mar 22 2017 5 30 58 pm](https://cloud.githubusercontent.com/assets/1182341/24221606/59e40838-0f25-11e7-9151-7c1ab804c8c1.png)

**Comment by ryancoughlin** [comment]
I am doing this for now and it does work. Not sure if there is a more elegant way: 

```
this.savedGradientText.fadeIn(200).then(() => {
  this.savedGradientText.fadeOutUp(2000)
})
```
