### ISSUE TITLE
RN 0.37.0: ScrollView "viewConfig" is not defined

### ISSUE THREAD

**Issue by joncursi** [oblador/react-native-animatable#70]
Hi! I just upgraded to RN 0.37.0 and got this error when I booted up my app:

<img width="388" alt="screen shot 2016-11-09 at 4 19 55 am" src="https://cloud.githubusercontent.com/assets/4974609/20133028/cab2a9f8-a633-11e6-850b-fff7bbdf47ba.png">

I searched all of my javascript for any instances of `viewConfig` and couldn't find any, so this seems to be an issue inside this library, particularly the `animation` prop on ScrollView.

```jsx
const ScrollView = createAnimatableComponent(ReactNative.ScrollView);

        <ScrollView
          animation="fadeIn"
          ...
        />
```

Reference: https://github.com/facebook/react-native/issues/10825

**Comment by oblador** [comment]
My fix was released in 0.38 and it works well now for all I know.
