### ISSUE TITLE
onAnimationEnd not work

### ISSUE THREAD

**Issue by agustinramos** [oblador/react-native-animatable#71]
onAnimationEnd parameter does not work

Example:
         <Animatable.View ref="view" delay={30} duration={2200} 
                             animation='fadeInUp' iterationCount='infinite' 
                             onAnimationBegin={()=>console.log('start')}
                             onAnimationEnd={()=>console.log('end')} >
              <Text style={styles.sectionIcon}>
                <Icon name='arrow-up' size={Metrics.icons.xxxl} color={Colors.silver} />
              </Text>            
         </Animatable.View>

**Comment by oblador** [comment]
It's because your animation is infinite.
