### ISSUE TITLE
this._transforms.forEach is not a function when animating a transform

### ISSUE THREAD

**Issue by danieldunderfelt** [oblador/react-native-animatable#72]
Hi!

I'm trying to animate the `translateY`value like this:

```
this.animView.transitionTo({
  height: 80,
  transform: [{ translateY: 30 }]
})
```

But `animatable` crashes with the message:

```
this._transforms.forEach is not a function

AnimatedTransform.__attach
on line 1373 of AnimatedImplementation.js
```

Removing the transform style makes it work. Also, using `translateY` directly, without the `transform` prop, also works.

**Comment by danieldunderfelt** [comment]
The `custom-animations` branch also has this bug :(

**Comment by oblador** [comment]
Hey, try the `custom-animations` branch now!

**Comment by danieldunderfelt** [comment]
I can confirm this works in v1! Thanks @oblador!
