### ISSUE TITLE
Contineous rotation for clock

### ISSUE THREAD

**Issue by julesmoretti** [oblador/react-native-animatable#74]
Say I was to have a View rotate around a circle and I would like for it to transition smoothly. How could I prevent it to go backwards accross the whole circle when reaching the 360 degrees > 0...

Here is an exemple of the function.

```
<Animatable.View
	transition='rotate'
	duration={200}
	easing='ease-in-out'
	style={[
		styles.armHolder,
		{ transform: [{rotate: this.state.degrees+'deg'}]}
		]}>
```

Thank you.

**Comment by oblador** [comment]
I haven't tried this but if you use 370deg instead of 10deg I don't think it should animate backwards.

**Comment by julesmoretti** [comment]
Thank you for this. I am pretty sure that the 370deg would work but at one point the function will have to reset back to a lower value otherwise the numbers will become astronomical.

So one solution would be to disable the animation when it reaches 370deg, change it to 10deg and then resume the animation... but there is no real straightforward way to achieve this as far as I am aware.

What do you think?

Thank you.

**Comment by oblador** [comment]
I think you'd have to implement this with regular `Animated` if you want to reset the value without transitioning.
