### ISSUE TITLE
FR: Animate on unmount

### ISSUE THREAD

**Issue by kyle-ssg** [oblador/react-native-animatable#8]
Hey, I've been looking for something like this so may use it as a starting point! What'd be really cool is if we can define both in and out transitions, this would be particularly good for list views - having them do something more interesting on unmount.

Looking at the current setup this would mean animationIn / animationOut would probably be passed in as an object.

**Comment by oblador** [comment]
Hi, that's a cool idea but unfortunately I don't think it's possible to do it on `componentWillUnmount`. But I should definitively add something like promises that resolve after completed animation that will enable you to do something like this.

**Comment by oblador** [comment]
Promises are here!
