### ISSUE TITLE
Unknown named module 

### ISSUE THREAD

**Issue by johneisenheim** [oblador/react-native-animatable#82]
Hi there!
After installed react-native-animatable with classic 

`npm install --save react-native animatable`

when I try to import in my js file by 

`import * as Animatable from 'react-native-animatable';`

RN shows me the error

`Unknown named module 'react-native-animatable'`

How can I fix this? 

Thank you so much!

**Comment by williamtran29** [comment]
npm install --save react-native-animatable
not "npm install --save react-native animatable"

**Comment by johneisenheim** [comment]
@williamtran29 Sure, typo error, sorry. Anyway, I solved it deleting and re-installing mobile application. Everything seems to work now!

Thank you!
