### ISSUE TITLE
white pages when moving marbles

### ISSUE THREAD

**Issue by 2ducanhpham** [oblador/react-native-animatable#83]
white pages when moving ball, but click on the current

**Comment by oblador** [comment]
Sorry, but I don't understand.

**Comment by 2ducanhpham** [comment]
![simulator screen shot dec 6 2016 1 43 41 pm](https://cloud.githubusercontent.com/assets/14899775/20915712/184abc96-bbba-11e6-8b5e-f9f44652e542.png)
![simulator screen shot dec 6 2016 1 43 50 pm](https://cloud.githubusercontent.com/assets/14899775/20915713/184f58aa-bbba-11e6-849a-36774f29d138.png)

first render blank, but i click or drag .it show

**Comment by 2ducanhpham** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14899775/20916244/5334950e-bbbd-11e6-8262-e4f34ff04012.gif)

**Comment by oblador** [comment]
Do you have a minimal example to reproduce it? I'm suspecting it has to do with `removeClippedSubviews` in RN core, why do you think it's a bug with this module?
