### ISSUE TITLE
Slide out animations only go 100px out of view

### ISSUE THREAD

**Issue by dantman** [oblador/react-native-animatable#86]
translate{X,Y} values in RN are in pixels, not percents. So the `100` values inside `definitions/sliding-exits.js` mean that slide out animations are hardcoded to only move 100 px out of the viewing area.

Which leads to them breaking when the view in question is larger than 100 in that direction.

**Comment by mcavaliere** [comment]
@dantman I managed to work around this with a custom animation: 

```js
const mySlideOutDown = {
    from: {
      height: 400,
    },
    to: {
      height: 0,
    }
}

const mySlideInUp = {
    from: {
      height: 0,
    },
    to: {
      height: 400,
    }
}

Animatable.initializeRegistryWithDefinitions({
  mySlideInUp: mySlideInUp,
  mySlideOutDown: mySlideOutDown
});
```

**Comment by Rovack** [comment]
The workaround looks good, but are there any plans to actually solve the issue with sliding-exits?
Seems this has been open without response for over 6 months now...

**Comment by oblador** [comment]
This issue is actually solved since a long time with the introduction of custom animations like @mcavaliere mentioned, so I'm gonna close this.
