### ISSUE TITLE
Callback on Animation finished & React Native animated exist discussion 

### ISSUE THREAD

**Issue by imton** [oblador/react-native-animatable#9]
Hey Joel, awesome work here! 

I am doing this sharing sheet modal

![Demo](http://i.giphy.com/3o8doP67Yu4wGPXtuM.gif)

I was mounting this component using

```.... { this.state.shouldShareIt && <ShareModal />````

Everything is find for entrance animation, but the tricky part (we should discuss) is the delete/exit part.

Using that pattern, the component would be ripped out as soon as ```this.state.shouldShareIt``` is false. 

So far what I did is to toggle ```` bounceInUp ``` / ```bounceOutDown``` but this always renders the modal even when it is hidden off-screen-bounds.

The first thing we need to start thinking for some solutions is at least a callback for when animations are done, did I miss this property? 

Would love to hear your thoughts on this. I know the core team of RN has some discussion on this issue for LayoutAnimations and the issues are still open (specially for animation of deleted elements which are not currently handled)

Best

**Comment by oblador** [comment]
Haha, awesome screen! Callbacks is a thing I want to support. I hope to have some time to implement this during the holidays.

**Comment by oblador** [comment]
As of [0.4.1](https://github.com/oblador/react-native-animatable/releases/tag/v0.4.1) you can now `component.bounceOutDown().then(() => this.setState({shouldShareIt: false})`.

**Comment by imton** [comment]
:clap: :christmas_tree: :fireworks: :smile:
