### ISSUE TITLE
Multiple animation properties

### ISSUE THREAD

**Issue by JulianKingman** [oblador/react-native-animatable#94]
It would be great if I could do something like `<AnimateableComponent animation="zoomIn zoomOut">...</AnimateableComponent>`

**Comment by oblador** [comment]
Hmm, zoom in and zoom out at the same time? Doesn't make sense to me. You can nest Animatable components, but it's going to be hard when animations want to animate the same properties in the same component but to different values.

**Comment by JulianKingman** [comment]
I would expect a component with the above properties to zoomIn on mount, and zoomOut on unmount.

**Comment by oblador** [comment]
Unmount animations are not supported and honestly don't know how they could be implemented outside of react native core.

**Comment by JulianKingman** [comment]
Good point. It would take unmounting the component in the callback function of an animation, which is probably best left up to the developer.
