### ISSUE TITLE
Fades from white?

### ISSUE THREAD

**Issue by JulianKingman** [oblador/react-native-animatable#95]
I created an animation like so: 

````jsx
<AnimatedView
              animation="fadeInUp"
              useNativeDriver
              duration={300}
              style={{backgroundColor: 'rgba(0,0,0,0)'}}
              ref={(component) => {
                this.animatedModal = component;
              }}
            >
// ...etc
````

And before fading in, it turns the whole screen white. I slowed the animation way down to see the effect:

![gif](https://cloud.githubusercontent.com/assets/1566400/22434999/53fb973a-e6ec-11e6-8cfd-0357770b971d.gif)

**Comment by oblador** [comment]
It uses opacity, change the color of your background to something other than white if you want to achieve another effect.

**Comment by JulianKingman** [comment]
The background behind the modal is being covered by a white element as soon as the animation starts, I'm wondering where that element came from. I should be able to see the original background under the translucent modal (which you can only see for a moment in the gif).

**Comment by oblador** [comment]
Not sure how you display the modal, but it's likely from whatever navigation lib you are using or the modal component itself.

**Comment by JulianKingman** [comment]
You are correct. The native Modal has a white background. For now I'm just using the built in animations, so I'm not sure what happens if you put a transparent background on the Modal, but this is solved for me in either case. Thanks!
